site_name: C Programming Knowledge
theme:
  name: material
nav:
  - Home: index.md
  - Tutorials:
      - Basics: tutorials/basics.md
      - Hello World: tutorials/hello_world.md
      - Variables & Arithmetic: tutorials/c_variables_arithmetic.md
      - Arithmetic Operations: tutorials/c_arrithmetic.md
      - Control Structures: tutorials/c_control_structures_one.md
      - Loops: tutorials/c_loops.md
      - Input & Output: tutorials/c_input_output_notes.md
      - Functions & Structure: tutorials/c_functions_and_structure_notes.md
      - Pointers & Arrays: tutorials/c_pointers_and_arrays_notes.md
      - Symbolic Constants: tutorials/c_symbolic_constants.md
      - File Read & Create: tutorials/c_file_read_and_create.md
      - Text Processing: tutorials/c_text_processing_examples.md
      - UNIX System Interface: tutorials/c_unix_system_interface_notes.md
  - Examples:
      - Array Examples: examples/c_array_examples.c
      - Arithmetic Example: examples/c_arrithmetic.c
      - Basic Part One: examples/c_basic_part_one.c
      - Control Structures: examples/c_control_structures_one.c
      - File Read & Create: examples/c_file_read_and_create.c
      - Hello World: examples/c_first_code_hello_world.c
      - Function Examples: examples/c_function_examples.c
      - Functions & Structure Notes: examples/c_functions_and_structure_notes.c
      - Input Output Notes: examples/c_input_output_notes.c
      - Line Input: examples/c_line_input.c
      - Loops: examples/c_loops.c
      - Number Guessing Game: examples/c_number_guessing_game.c
      - Pointers & Arrays Notes: examples/c_pointers_and_arrays_notes.c
      - stdio.h Note: examples/c_stdio_h_note.md
      - String Examples: examples/c_string_examples.c
      - Symbolic Constants: examples/c_symbolic_constants.c
      - Text Processing: examples/c_text_processing_examples.c
      - UNIX System Interface Notes: examples/c_unix_system_interface_notes.c
      - Variables & Arithmetic: examples/c_variables_arithmetic.c